# Generated by Django 5.1 on 2025-08-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elemen1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilihan', models.TextField()),
                ('lokasi', models.TextField()),
                ('butiran', models.TextField()),
            ],
        ),
    ]
