# Generated by Django 5.1 on 2025-08-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideabadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_lokasi', models.CharField(max_length=255)),
            ],
        ),
    ]
