# Generated by Django 5.1 on 2025-08-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideabadmin', '0002_lokasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lokasi',
            name='id',
        ),
        migrations.AddField(
            model_name='lokasi',
            name='lid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
