# Generated by Django 5.1 on 2025-08-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideabadmin', '0005_alter_lokasi_lid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasi',
            name='lid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
